# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
strategy:
  matrix:
    matrixone:
      vmImage: ubuntu-latest
    matrixtwo:
      vmImage: ubuntu-latest

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest
  - centos-latest
- name: runPerfTests
  type: boolean
  default: false

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  condition: runPerfTests
  displayName: 'Run a multi-line script'
